# Generated by Django 2.2.17 on 2021-01-16 07:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TapLinkByVlasov', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TapButton',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название')),
                ('url', models.URLField(verbose_name='ссылка')),
                ('tap', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TapLinkByVlasov.TapLink')),
            ],
        ),
        migrations.DeleteModel(
            name='TapLinkButton',
        ),
    ]
