# Generated by Django 2.2.17 on 2021-01-11 13:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogBase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Заголовок')),
                ('description', models.CharField(max_length=100, verbose_name='Описание')),
                ('index', models.PositiveIntegerField(default=0, verbose_name='индекс')),
            ],
        ),
        migrations.CreateModel(
            name='BlogText',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Text')),
                ('index', models.PositiveIntegerField(default=0, verbose_name='индекс')),
                ('blog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BlogSystem.BlogBase')),
            ],
        ),
        migrations.CreateModel(
            name='BlogImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='/images/blog/blog_1.png', upload_to='images/')),
                ('index', models.PositiveIntegerField(default=0, verbose_name='индекс')),
                ('blog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BlogSystem.BlogBase')),
            ],
        ),
    ]
