# Generated by Django 2.2.17 on 2021-01-14 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BlogSystem', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogbase',
            name='preview',
            field=models.ImageField(default='/images/blog/blog_1.png', upload_to='images/'),
        ),
    ]
