# Generated by Django 2.2.8 on 2019-12-27 23:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.PositiveIntegerField(default=0, verbose_name='Баланс')),
                ('is_teacher', models.BooleanField(default=False, verbose_name='Преподаватель')),
                ('age', models.PositiveIntegerField(default=0, verbose_name='Возраст')),
                ('activity', models.CharField(choices=[('minimal', 'Минимальная активность'), ('low', 'Cлабый уровень активности'), ('mid', 'Умеренный уровень активности'), ('high', 'Тяжелая или трудоемкая активность'), ('very_high', 'Экстремальный уровень')], max_length=50, verbose_name='Активность')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
