# Generated by Django 2.2.8 on 2020-02-08 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accaunt', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='cover',
            field=models.ImageField(default='media/images/icon_0.png', upload_to='images/'),
        ),
    ]
