# Generated by Django 2.2.8 on 2020-02-08 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accaunt', '0003_auto_20200208_1829'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='isCommunity',
            field=models.BooleanField(default=False),
        ),
    ]
