# Generated by Django 2.2.8 on 2020-04-17 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accaunt', '0004_profile_iscommunity'),
    ]

    operations = [
        migrations.CreateModel(
            name='shopitem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cource_id', models.PositiveIntegerField(default=0, verbose_name='Номер курса')),
                ('price', models.PositiveIntegerField(default=0, verbose_name='Цена курса')),
                ('discount', models.PositiveIntegerField(default=0, verbose_name='Цена курса')),
            ],
        ),
    ]
