# Generated by Django 2.2.8 on 2020-04-18 07:14

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Accaunt', '0006_unitypay'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='unitypay',
            new_name='unitpay',
        ),
    ]
