# Generated by Django 2.2.8 on 2020-04-18 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accaunt', '0008_purchase'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchase',
            name='user',
        ),
        migrations.AddField(
            model_name='purchase',
            name='userid',
            field=models.PositiveIntegerField(default=0, verbose_name='Номер курса'),
        ),
    ]
