# Generated by Django 2.2.8 on 2020-04-19 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accaunt', '0009_auto_20200418_1630'),
    ]

    operations = [
        migrations.CreateModel(
            name='itemshop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cource_id', models.PositiveIntegerField(default=0, verbose_name='Номер товара')),
                ('price', models.PositiveIntegerField(default=0, verbose_name='Цена курса')),
                ('discount', models.PositiveIntegerField(default=0, verbose_name='Скидка')),
            ],
        ),
        migrations.DeleteModel(
            name='unitpay',
        ),
    ]
