# Generated by Django 2.2.8 on 2020-04-19 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accaunt', '0010_auto_20200419_2011'),
    ]

    operations = [
        migrations.CreateModel(
            name='moneyoper',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.PositiveIntegerField(default=0, verbose_name='UserID')),
                ('is_rashod', models.BooleanField(default=False, verbose_name='Расход')),
                ('price', models.PositiveIntegerField(default=0, verbose_name='Цена')),
                ('data', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
