# Generated by Django 2.2.17 on 2021-01-02 08:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Accaunt', '0011_moneyoper'),
    ]

    operations = [
        migrations.DeleteModel(
            name='itemshop',
        ),
        migrations.DeleteModel(
            name='moneyoper',
        ),
        migrations.DeleteModel(
            name='purchase',
        ),
        migrations.DeleteModel(
            name='shopitem',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='activity',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='age',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='balance',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='isCommunity',
        ),
    ]
