# Generated by Django 2.2.17 on 2021-02-07 11:04

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Accaunt', '0013_resttockenpassword'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resttockenpassword',
            name='user',
        ),
        migrations.AddField(
            model_name='resttockenpassword',
            name='user',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
