# Generated by Django 2.2.17 on 2021-02-07 11:17

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Accaunt', '0014_auto_20210207_1804'),
    ]

    operations = [
        migrations.CreateModel(
            name='restPasswordTocken',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tocken', models.CharField(max_length=200, verbose_name='Токен авторизации')),
                ('created', models.DateTimeField(blank=True, default=datetime.datetime.now, editable=False, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='restTockenPassword',
        ),
    ]
