# Generated by Django 2.2.17 on 2021-01-02 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CourceInstance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.PositiveIntegerField(default=0, verbose_name='Номер пользователя')),
                ('cource_id', models.PositiveIntegerField(default=0, verbose_name='Номер курса')),
            ],
        ),
        migrations.CreateModel(
            name='LearnCource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cource_id', models.PositiveIntegerField(default=0, verbose_name='Номер курса')),
                ('name', models.CharField(default='Название!', max_length=100, verbose_name='Название')),
            ],
        ),
        migrations.CreateModel(
            name='LearnModule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cource_id', models.PositiveIntegerField(default=0, verbose_name='Номер курса')),
                ('name', models.CharField(default='Название!', max_length=100, verbose_name='Название')),
            ],
        ),
        migrations.CreateModel(
            name='LearnTheme',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module_id', models.PositiveIntegerField(default=0, verbose_name='Номер курса')),
                ('name', models.CharField(default='Название!', max_length=100, verbose_name='Название')),
            ],
        ),
        migrations.CreateModel(
            name='ModuleInstance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module_id', models.PositiveIntegerField(default=0, verbose_name='Номер курса')),
                ('cource_id', models.PositiveIntegerField(default=0, verbose_name='Номер курса')),
            ],
        ),
        migrations.CreateModel(
            name='ThemeInstance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module_id', models.PositiveIntegerField(default=0, verbose_name='Номер модуля')),
                ('theme_id', models.PositiveIntegerField(default=0, verbose_name='Номер темы')),
            ],
        ),
    ]
