# Generated by Django 2.2.17 on 2021-01-02 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LearnSystem', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ModuleInstance',
        ),
        migrations.DeleteModel(
            name='ThemeInstance',
        ),
        migrations.AlterField(
            model_name='learncource',
            name='name',
            field=models.CharField(default='Название!', max_length=100, verbose_name='Заголовок курса'),
        ),
        migrations.AlterField(
            model_name='learnmodule',
            name='name',
            field=models.CharField(default='Название!', max_length=100, verbose_name='Заголовок модуля'),
        ),
        migrations.AlterField(
            model_name='learntheme',
            name='module_id',
            field=models.PositiveIntegerField(default=0, verbose_name='Номер модуля'),
        ),
        migrations.AlterField(
            model_name='learntheme',
            name='name',
            field=models.CharField(default='Название!', max_length=100, verbose_name='Тема'),
        ),
    ]
