# Generated by Django 2.2.17 on 2021-01-02 15:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('LearnSystem', '0002_auto_20210102_2248'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courceinstance',
            name='user_id',
        ),
        migrations.AddField(
            model_name='courceinstance',
            name='user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
