# Generated by Django 2.2.17 on 2021-01-03 16:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('LearnSystem', '0003_auto_20210102_2256'),
    ]

    operations = [
        migrations.CreateModel(
            name='ThemeImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='/images/themes/theme_1.png', upload_to='images/')),
                ('description', models.CharField(max_length=100, verbose_name='Описание')),
                ('theme', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='LearnSystem.LearnTheme')),
            ],
        ),
        migrations.CreateModel(
            name='ThemeBase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Заголовок')),
                ('description', models.CharField(max_length=100, verbose_name='Описание')),
                ('theme', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='LearnSystem.LearnTheme')),
            ],
        ),
    ]
