# Generated by Django 2.2.17 on 2021-01-04 07:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('LearnSystem', '0004_themebase_themeimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='themeimage',
            name='theme',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LearnSystem.LearnTheme'),
        ),
    ]
