# Generated by Django 2.2.17 on 2021-01-04 07:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('LearnSystem', '0005_auto_20210104_1420'),
    ]

    operations = [
        migrations.AlterField(
            model_name='themebase',
            name='theme',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LearnSystem.LearnTheme'),
        ),
    ]
