# Generated by Django 2.2.17 on 2021-01-04 08:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('LearnSystem', '0006_auto_20210104_1425'),
    ]

    operations = [
        migrations.AddField(
            model_name='themebase',
            name='body',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='ThemeBody',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField(verbose_name='Текст')),
                ('theme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LearnSystem.LearnTheme')),
            ],
        ),
    ]
