# Generated by Django 2.2.17 on 2021-01-04 17:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('LearnSystem', '0008_remove_themebase_body'),
    ]

    operations = [
        migrations.CreateModel(
            name='ThemeVideo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.FileField(upload_to='videos/')),
                ('theme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LearnSystem.LearnTheme')),
            ],
        ),
    ]
