# Generated by Django 2.2.17 on 2021-01-05 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LearnSystem', '0009_themevideo'),
    ]

    operations = [
        migrations.AddField(
            model_name='themebase',
            name='index',
            field=models.PositiveIntegerField(default=0, verbose_name='индекс'),
        ),
        migrations.AddField(
            model_name='themebody',
            name='index',
            field=models.PositiveIntegerField(default=0, verbose_name='индекс'),
        ),
        migrations.AddField(
            model_name='themeimage',
            name='index',
            field=models.PositiveIntegerField(default=0, verbose_name='индекс'),
        ),
        migrations.AddField(
            model_name='themevideo',
            name='index',
            field=models.PositiveIntegerField(default=0, verbose_name='индекс'),
        ),
    ]
