# Generated by Django 2.2.17 on 2021-01-05 08:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('LearnSystem', '0010_auto_20210105_1319'),
    ]

    operations = [
        migrations.AddField(
            model_name='courceinstance',
            name='is_EndCource',
            field=models.BooleanField(default=1, verbose_name='Курс закончен'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='learntheme',
            name='is_Completed',
            field=models.BooleanField(default=1, verbose_name='Темаы'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='courceinstance',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
