# Generated by Django 2.2.17 on 2021-01-07 09:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LearnSystem', '0011_auto_20210105_1528'),
    ]

    operations = [
        migrations.CreateModel(
            name='Webinar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Заголовок')),
                ('description', models.CharField(max_length=100, verbose_name='Описание')),
                ('guid', models.CharField(max_length=255)),
                ('image', models.ImageField(default='/images/webinar/webinar_1.png', upload_to='images/')),
                ('created', models.DateTimeField(blank=True, default=datetime.datetime.now, editable=False, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='message',
            name='user',
        ),
    ]
