# Generated by Django 2.2.17 on 2021-01-12 11:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('LearnSystem', '0014_auto_20210111_2005'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='learnmodule',
            name='cource_id',
        ),
        migrations.RemoveField(
            model_name='learntheme',
            name='module_id',
        ),
        migrations.AddField(
            model_name='learnmodule',
            name='cource',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='LearnSystem.LearnCource'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='learntheme',
            name='module',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='LearnSystem.LearnModule'),
            preserve_default=False,
        ),
    ]
