# Generated by Django 2.2.17 on 2021-01-12 13:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('LearnSystem', '0015_auto_20210112_1801'),
    ]

    operations = [
        migrations.CreateModel(
            name='StatsCource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('progressToDay', models.PositiveIntegerField(default=0, verbose_name='Прогресс за день')),
                ('datetime', models.DateTimeField(verbose_name='день')),
                ('cource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LearnSystem.CourceInstance')),
            ],
        ),
    ]
