# Generated by Django 2.2.17 on 2021-01-25 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LearnSystem', '0016_statscource'),
    ]

    operations = [
        migrations.AddField(
            model_name='webinar',
            name='id_webinar',
            field=models.PositiveIntegerField(default=3188, verbose_name='индекс'),
        ),
    ]
