# Generated by Django 2.2.17 on 2021-01-25 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LearnSystem', '0017_webinar_id_webinar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='webinar',
            name='id_webinar',
            field=models.PositiveIntegerField(default=478, verbose_name='индекс'),
        ),
    ]
