# Generated by Django 2.2.17 on 2021-01-25 10:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LearnSystem', '0018_auto_20210125_1637'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailClient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, verbose_name='Почта клиента')),
                ('username', models.CharField(max_length=100, verbose_name='Описание')),
                ('created', models.DateTimeField(blank=True, default=datetime.datetime.now, editable=False, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='webinar',
            name='id_webinar',
            field=models.PositiveIntegerField(default=8916, verbose_name='индекс'),
        ),
    ]
