# Generated by Django 2.2.17 on 2021-02-07 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LearnSystem', '0019_auto_20210125_1715'),
    ]

    operations = [
        migrations.AlterField(
            model_name='webinar',
            name='id_webinar',
            field=models.PositiveIntegerField(default=865, verbose_name='индекс'),
        ),
    ]
