# Generated by Django 2.2.17 on 2021-02-07 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LearnSystem', '0021_auto_20210207_1747'),
    ]

    operations = [
        migrations.AlterField(
            model_name='webinar',
            name='id_webinar',
            field=models.PositiveIntegerField(default=7857, verbose_name='индекс'),
        ),
    ]
