# Generated by Django 2.2.17 on 2021-02-07 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LearnSystem', '0022_auto_20210207_1804'),
    ]

    operations = [
        migrations.AlterField(
            model_name='webinar',
            name='id_webinar',
            field=models.PositiveIntegerField(default=6785, verbose_name='индекс'),
        ),
    ]
