# Generated by Django 2.2.17 on 2021-03-01 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LearnSystem', '0023_auto_20210207_1817'),
    ]

    operations = [
        migrations.AddField(
            model_name='courceinstance',
            name='Name',
            field=models.CharField(default='Курс', max_length=100, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='courceinstance',
            name='image',
            field=models.ImageField(default='/images/themes/theme_1.png', upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='webinar',
            name='id_webinar',
            field=models.PositiveIntegerField(default=8250, verbose_name='индекс'),
        ),
    ]
