# Generated by Django 2.2.17 on 2021-03-03 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LearnSystem', '0023_auto_20210207_1817'),
    ]

    operations = [
        migrations.AlterField(
            model_name='webinar',
            name='id_webinar',
            field=models.PositiveIntegerField(default=9218, verbose_name='индекс'),
        ),
    ]
